// Code generated by "stringer -type=OrderBySQLi"; DO NOT EDIT.

package pgsql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DateOfBirth-0]
	_ = x[Email-1]
	_ = x[FirstName-2]
	_ = x[LastName-3]
	_ = x[Phone-4]
	_ = x[StreetAddress-5]
	_ = x[Consented-6]
	_ = x[Verified-7]
	_ = x[Origin-8]
	_ = x[CustomFields-9]
	_ = x[Name-10]
	_ = x[MerkleRoot-11]
	_ = x[MerkleTreeURI-12]
	_ = x[Size-13]
	_ = x[CreatedAt-14]
	_ = x[UpdatedAt-15]
}

const _OrderBySQLi_name = "DateOfBirthEmailFirstNameLastNamePhoneStreetAddressConsentedVerifiedOriginCustomFieldsNameMerkleRootMerkleTreeURISizeCreatedAtUpdatedAt"

var _OrderBySQLi_index = [...]uint8{0, 11, 16, 25, 33, 38, 51, 60, 68, 74, 86, 90, 100, 113, 117, 126, 135}

func (i OrderBySQLi) String() string {
	if i < 0 || i >= OrderBySQLi(len(_OrderBySQLi_index)-1) {
		return "OrderBySQLi(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderBySQLi_name[_OrderBySQLi_index[i]:_OrderBySQLi_index[i+1]]
}
