// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CensusMembers string
	Censuses      string
	Entities      string
	Members       string
	PushTokens    string
	Targets       string
	Users         string
}{
	CensusMembers: "census_members",
	Censuses:      "censuses",
	Entities:      "entities",
	Members:       "members",
	PushTokens:    "push_tokens",
	Targets:       "targets",
	Users:         "users",
}
