// Code generated by SQLBoiler 4.1.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Censuses", testCensusesUpsert)

	t.Run("Entities", testEntitiesUpsert)

	t.Run("Members", testMembersUpsert)

	t.Run("PushTokens", testPushTokensUpsert)

	t.Run("Targets", testTargetsUpsert)

	t.Run("Users", testUsersUpsert)
}
