---

name: Main

on: [push, pull_request]

jobs:
  go-tests:
    runs-on: self-hosted
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Go test
      run: |
          # we run vet in another step
          go test -vet=off -timeout=1m ./...
          # -race can easily make the crypto stuff 10x slower
          go test -vet=off -timeout=10m -race -covermode atomic -coverprofile=covprofile ./...

    - name: Go analyze
      run: |
        diff -u <(echo -n) <(gofmt -s -d $(git ls-files '*.go'))
        go vet ./...
        curl -L https://github.com/dominikh/go-tools/releases/download/2020.2.3/staticcheck_linux_amd64.tar.gz | tar -xzf -
        ./staticcheck/staticcheck ./...

    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    - name: Send coverage to coverall.io
      env:
        COVERALLS_TOKEN: ${{ secrets.github_token }}
      run: goveralls -coverprofile=covprofile -service=github

  docker-release:
    runs-on: self-hosted
    needs: [go-tests]
    if:
      github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage' ||  startsWith(github.ref, 'refs/heads/release')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Get short branch name
        id: var
        shell: bash
        # Grab the short branch name, convert slashes to dashes
        run: |
         echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )"

      - name: Push to Docker Hub and ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            vocdoni/${{ github.event.repository.name }}:latest, vocdoni/${{ github.event.repository.name }}:${{ steps.var.outputs.branch }},
            ghcr.io/vocdoni/${{ github.event.repository.name }}:latest,ghcr.io/vocdoni/${{ github.event.repository.name }}:${{ steps.var.outputs.branch }}

      - name: Push to Docker Hub and ghcr.io (notifications)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          target: dvotenotif
          push: true
          tags: |
            vocdoni/${{ github.event.repository.name }}:notif-latest, vocdoni/${{ github.event.repository.name }}:notif-${{ steps.var.outputs.branch }},
            ghcr.io/vocdoni/${{ github.event.repository.name }}:notif-latest,ghcr.io/vocdoni/${{ github.event.repository.name }}:notif-${{ steps.var.outputs.branch }}
